name: '${project.name}'
version: '${project.version}'
main: pl.ynfuien.yresizingborders.YResizingBorders
api-version: '1.20'
softdepend: [PlaceholderAPI]
author: Ynfuien
description: '${project.description}'
website: '${project.url}'

commands:
  yresizingborders:
    aliases: [yrb]
    description: Main and only plugin's command
    permission: yresizingborders.command